### ISSUE TITLE
build速度会很慢的

### ISSUE THREAD

**Issue by tianhm** [pchaos/Docker-hikyuu#1]
建议：将下载anaconda改成从国内清华大学的镜像下载。boost从网易的linux源下载。这样速度很快很多。

**Comment by pchaos** [comment]
在我这里，清华镜像也很慢。所以就没有从清华下载了。
网易也是，我这里网易速度时快时慢。
不知道还有什么办法？

**Comment by pchaos** [comment]
对于很慢的，我建议用第三方工具先下载下来，再复制到响应的目录
